[
   Module                       -- KW["module"] _1 _2,
   Module.2:iter-star           -- _1,
   Entity                       -- KW["entity"] _1 KW["{"] _2 KW["}"],
   Entity.2:iter-star           -- _1,
   Attribute                    -- _1 KW[":"] _2,
   String                       -- KW["String"],
   Int                          -- KW["Int"],
   Relation                     -- KW["relation"] _1 KW["{"] _2 KW["}"],
   Relation.2:iter-star         -- _1,
   Member                       -- _1 KW[":"] _2,
   EntityType                   -- _1,
   COMPLETION-Start             -- _1,
   COMPLETION-Attribute         -- _1,
   COMPLETION-PrimitiveType     -- _1,
   COMPLETION-Definition        -- _1,
   COMPLETION-MemberOrAttribute -- _1,
   COMPLETION-Member            -- _1,
   COMPLETION-EntityType        -- _1,
   Identifier                   -- _1,
   COMPLETION-Identifier        -- _1
]